development:
  # Configure available database clients. (required)
  clients:
    default:
      uri: <%= ENV['MONGO_URL'] %>
      options:
        heartbeat_frequency: 1
        read:
            mode: <%= ENV['MONGO_READ_MODE']||"primary" %>
        max_pool_size: 100
test:
  clients:
    default:
      database: whatnow_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
  clients:
    default:
      uri: <%= ENV['MONGO_URL'] %>
      options:
        max_pool_size: <%= (ENV['MONGO_POOL_SIZE']||"300").to_i %>
        heartbeat_frequency: 1
        read:
            mode: <%= ENV['MONGO_READ_MODE']||"primary" %>